### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#51]
We export in the ARS system, but BIDS only compatible with the RAS system now (see also this post below)

https://github.com/bids-standard/bids-specification/issues/701

Once the issue is resolved:
- We might have to export to RAS (rotate channels)
- Rotate them back to ARS when we import BIDS data

**Comment by dungscout96** [comment]
For now we circumvent it by putting "Other" as EEGCoordinateSystem and "EEGLAB" in EEGCoordinateSystemDescription. Once EEGLAB is accepted we'll change EEGCoordinateSystem to "EEGLAB".
Implemented in EEGCoordinateSystem

**Comment by BjoernHoltze** [comment]
Before and after exporting my dataset into BIDS, in EEGLAB the electrodes were represented according to the ALS system but not according to the ARS system and the units were not given in mm since the spherical radius was 1. When I checked the sample data from EEGLAB 2020_0, the units seemed to be in mm as the spherical radius was about 88, but the electrodes were also represented according to the ALS. Thus, I have two questions: 
1) Is left and right switched in EEGLAB according to radiological terminology? 
2) Are you intending to integrate the option "normalized" for EEGCoordinateUnits if the spherical radius is equal to 1?

**Comment by arnodelorme** [comment]
To do:
- Clement to create web page describing our coordinate system
- Arno to send it to Stefan
- bids_export to set the coordinate system to EEGLAB
- bids_import to rotate Captrack system when BIDS data is imported

**Comment by sappelhoff** [comment]
Any news on this @arnodelorme @cll008? The web page really doesn't have to be big or shiny --> a couple of sentences describing the coordinate system will suffice!

Perhaps in the meantime these lines:

https://github.com/sccn/bids-matlab-tools/blob/801dacb7ea6ef262009150dbe7ba6873c446c480/bids_export.m#L951-L952

Can be changed so that it says: `"'EEGLAB':  ARS with origin exactly between LPA and RPA; X=Anterior Y=Right Z=Superior"`

That'd be more helpful than just `"EEGLAB"` WDYT?

**Comment by cll008** [comment]
Thanks for following up @sappelhoff .  I wrote a draft of a page but Arno and I are checking in with Scott on some things.

**Comment by sappelhoff** [comment]
@arnodelorme @cll008 have you seen my comment in https://github.com/bids-standard/bids-specification/issues/701#issuecomment-813911144 ?

We basically just need a documentation page for the `EEGLAB` coordinate system that we could link to ... then we can make a PR to allow that keyword in both specification and validator.

**Comment by cll008** [comment]
Thanks for the follow up @sappelhoff. Arno just made the [webpage](https://eeglab.org/tutorials/ConceptsGuide/coordinateSystem.html) live. The coordinate descriptions are correct but we are making some more edits to the rest of the text.

**Comment by sappelhoff** [comment]
> Thanks for the follow up @sappelhoff. Arno just made the webpage live. The coordinate descriptions are correct but we are making some more edits to the rest of the text.

That's looking good! I'll prepare two PRs (one to the BIDS spec, one to the BIDS validator) and will tag you in it so that you can review.
