### ISSUE TITLE
BIDS import look up channel locations

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#59]

**Comment by arnodelorme** [comment]
Done. Clement to check

**Comment by cll008** [comment]
Is EEG.chanlocs structure ever nonexistent (and not just blank?)
[~isfield(theta)](https://github.com/sccn/bids-matlab-tools/commit/720cd00a6f8427edb6fa6164e5d065cbb446cb43#diff-d9ee0e01064e30c819fe9a2b79c08281ec47f91adf17b586b5e49d1b23af470dR367) did not work on my test set since it had EEG.chanlocs.labels (and the other EEG.chanlocs structure's fields were existent but empty). If the fields are always present, then maybe we can cover our bases with `isempty(EEG.chanlocs.theta) || isempty(EEG.chanlocs.X) || isempty(EEG.chanlocs.sph_theta)` in case a dataset only has one of three types of coordinates?

**Comment by arnodelorme** [comment]
Sometimes it is blank. It should always be there though.
