### ISSUE TITLE
Electrode types

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#64]
Clement to edit default electrode file .elc for BEM model to .ced to add channel type.

**Comment by cll008** [comment]
Just tested things out with CED. We only care about channel label, x, y, z, and type for the BEM template. Two options:

1. Turn 'blankcells' back on[ when reading the text file ](https://github.com/sccn/eeglab/blob/ba072c3d70c42beb04821dbe184887c781957685/functions/sigprocfunc/readlocs.m#L456)so that format is preserved
2. Fill theta, sph* etc. columns with nans and add lines to ignore nans when writing to chanlocs structure

1 is more intuitive to me but can't be used if 'blankcells' is 'off' for a specific reason.

File wise, I'm thinking of naming it `standard-1005_BIDS.ced` and adding it to the BEM folder. Sound good?

**Comment by arnodelorme** [comment]
We should slightly modify the CED format so empty columns are allowed.

**Comment by cll008** [comment]
Well, CED allows empty columns and cells, the CED file itself doesn't become corrupted or anything.
I linked to the line in readlocs above, where 'blankcells' are not allowed. We can change this and things would work, but I don't know what it would break / why that is there to begin with: under what circumstances would a CED file have blank cells that should be ignored?

**Comment by arnodelorme** [comment]
Yes, we should fix readlocs to accept empty columns for CED. It is not a big deal because this CED file will always be released with a version of readlocs that supports it. As backup, we could save an SFP file with spherical coordinates though.
