### ISSUE TITLE
Issue with task info inconsistency across datasets

### ISSUE THREAD

**Issue by arnodelorme** [sccn/bids-matlab-tools#84]
@dungscout96 

Load the study below

/home/annalisa/Downloads/ds003061-IV 8.25.21

Select menu item File > BIDS > Edit task info

We get a warning message 

```
Warning: tInfo structures are inconsistent across datasets. Using first available tInfo of EEG(1)... 
> In pop_taskinfo/gettInfo (line 306)
In pop_taskinfo/preFill (line 243)
In pop_taskinfo (line 149) 
Using tInfo of EEG(1)...
```

Editing the task info, pressing OK and coming back should fix the issue (on the next call to this menu) but does not.

**Comment by dungscout96** [comment]
The problem is the checkbox `Use dataset "task condition" instead of task above`. It's actually not being handled well. Looking into this now and not sure how to handle this checkbox. Does it mean using EEG.condition for the task name? How should I handle inconsistency when there's a difference in EEG.condition among the datasets?

**Comment by arnodelorme** [comment]
Dung to do some minor tweak.

**Comment by dungscout96** [comment]
done in 984b443
